service: dmk-appengine-demo
runtime: java11
entrypoint: java -Xmx200m  -Xms200m -jar target/appengine-hello-1.0-SNAPSHOT.jar
instance_class: f1
automatic_scaling:
  max_instances: 3
#  min_instances: 1
#  max_idle_instances: 2
#  min_idle_instances: 1
